# Golang CircleCI 2.0 configuration
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
  test:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: ~/workdir
    steps:
      - checkout
      - run: echo "INTEGRATION TEST !!!"
      
  deploy:
    docker:
      - image: circleci/golang:1.11.5      
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: remove dummy tag
          command: |
            git push -u origin --delete dummy
  
  publish:
    docker:
      - image: circleci/node:12.6.0-alpine
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: publish to npm
          command: |
            npm -v
            
workflows:
  version: 2
  
  on_pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
              
  on_merge:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
              
  on_tag_release:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - deploy
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/

