# Golang CircleCI 2.0 configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/aaa
    steps:
      - checkout
      
  release_new:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: ~/aaa
    steps:
      - checkout
      - run:
          name: release new version
          command: |
            CURR_MBT_VERSION=$(cat ./VERSION)
            echo "Current release: ${CURR_MBT_VERSION}"
            MBT_VERSION=$(echo $CURR_MBT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "New release: ${MBT_VERSION}"
            #sed  -i "/\"version\":/s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./package.json
            #sed  -i "/cli_version:/s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./configs/version.yaml
            sed  -i "s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./VERSION
            cat ./VERSION
            git add ./package.json ./configs/version.yaml ./VERSION
            git config user.email "${MBT_REPO_USER_EMAIL}"
            git config user.name "Release Bot"
            git commit -m "Bump version ${MBT_VERSION}"
            # Push quietly to prevent showing the token in log
            git push -q  https://712f558540b64535ce41bfa244e2d377166214a2@github.com/michawai/aaa.git master
      #- run: curl -sL https://git.io/goreleaser | bash
      #- run: artifactdeployer pack --script-file ./configpack --package-file ./dist/cloud-mta-build-tool-pack -D baseDir=. -D mbtVersion=$MBT_VERSION
      #- run: artifactdeployer deploy --package-file ./dist/cloud-mta-build-tool-pack --artifact-version $MBT_VERSION --repo-url http://nexusmil.wdf.sap.corp:8081/nexus/content/repositories/sap.milestones.manual-uploads.hosted --repo-user $REPO_USER --repo-passwd $REPO_PASSWD
      #- run: npm publish .

workflows:
  version: 2
  build_integration:
    jobs:
      - build
  
  release:
    jobs:
      - release_new:
            filters:
              branches:
                only: develop
