# Golang CircleCI 2.0 configuration
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
  test:
    docker:
      - image: circleci/golang:1.13.3
    working_directory: ~/workdir
    steps:
      - checkout
      - run: echo "INTEGRATION TEST !!!"
      
  deploy:
    docker:
      - image: circleci/golang:1.13.3  
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: new release
          command: |
            #Tag
            #Make sure HEAD points to master
            git checkout master
            CURR_MBT_VERSION=$(cat ./VERSION)
            echo "Current release: ${CURR_MBT_VERSION}"
            MBT_VERSION=$(echo $CURR_MBT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "New release: ${MBT_VERSION}"
            sed  -i "s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./VERSION
            #Add all updated files to commit
            git add ./VERSION
            git config user.email "michawa@gmail.com"
            git config user.name "michawai"
            git commit -m "[skip ci] Bump version ${MBT_VERSION}"
            #Push commit directly to master
            git push -q https://github.com/michawai/aaa.git master
            git tag -a v${MBT_VERSION} -m "New release ${MBT_VERSION}"
            git push https://github.com/michawai/aaa.git v${MBT_VERSION}
            git checkout develop
            sed  -i "/ARG MBT_VERSION=/ s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./Dockerfile
            #Add all updated files to commit
            git add ./Dockerfile
            git config user.email "michawa@gmail.com"
            git config user.name "michawai"
            git commit -m "[skip ci] Bump version ${MBT_VERSION}"
            #Push commit directly to develop
            git push -q https://github.com/michawai/aaa.git develop
  
  publish:
    docker:
      - image: circleci/node:13.1.0
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: publish to npm
          command: |
            npm -v
            git push -u origin --delete dummy
                        
workflows:
  version: 2
  
  on_pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
              
  on_merge:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
              
  on_tag_release:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - deploy
          filters:
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
