# Golang CircleCI 2.0 configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
      
  release_new:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: release new version
          command: |
            CURR_MBT_VERSION=$(cat ./VERSION)
            echo "Current release: ${CURR_MBT_VERSION}"
            MBT_VERSION=$(echo $CURR_MBT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "New release: ${MBT_VERSION}"
            #sed  -i "/\"version\":/s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./package.json
            #sed  -i "/\"version\":/s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./internal/version/version_cfg.go
            #sed  -i "/cli_version:/s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./configs/version.yaml
            sed  -i "s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./VERSION
            cat ./VERSION
            git add ./VERSION
            git config user.email "${MBT_REPO_USER_EMAIL}"
            git config user.name "Release Bot"
            git commit -m "[skip ci] Bump version ${MBT_VERSION}"
            ## Push quietly to prevent showing the token in log
            git push -q  https://github.com/michawai/aaa.git develop
            echo 'export MBT_VERSION_NEW="$MBT_VERSION"' >> $BASH_ENV
      - run: 
          name: release new version
          command: echo New release ${MBT_VERSION_NEW}
      #- run: curl -sL https://git.io/goreleaser | bash
      #- run: npm publish .
      #- run: artifactdeployer pack --script-file ./configpack --package-file ./dist/cloud-mta-build-tool-pack -D baseDir=. -D mbtVersion=$MBT_VERSION
      #- run: artifactdeployer deploy --package-file ./dist/cloud-mta-build-tool-pack --artifact-version $MBT_VERSION --repo-url http://nexusmil.wdf.sap.corp:8081/nexus/content/repositories/sap.milestones.manual-uploads.hosted --repo-user $REPO_USER --repo-passwd $REPO_PASSWD
  
workflows:
  version: 2
  build_integration:
    jobs:
      - build
  
  release:
    jobs:
      - release_new:
            filters:
              branches:
                only: develop
