# Golang CircleCI 2.0 configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
      
  release_new:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
#      - run:
#          name: bump new version
#          command: |
#            MBT_VERSION=$(cat ./VERSION)
#            echo $MBT_VERSION
#      - run: 
#          name: release new version
#          command: curl -sL https://git.io/goreleaser | bash
#      - run: 
#          name: publish to npm
#          command: npm publish
      - run: 
          name: upload to nexus
          command: |
            MBT_VERSION=0.2.3
            echo $MBT_VERSION
            curl -L https://github.com/SAP/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Darwin_amd64.tar.gz -o cloud-mta-build-tool_${MBT_VERSION}_Darwin_amd64.tar.gz
            curl -L https://github.com/SAP/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Linux_amd64.tar.gz -o cloud-mta-build-tool_${MBT_VERSION}_Linux_amd64.tar.gz
            curl -L https://github.com/SAP/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Windows_amd64.tar.gz -o cloud-mta-build-tool_${MBT_VERSION}_Windows_amd64.tar.gz
            artifactdeployer pack --script-file ./configpack --package-file ./cloud-mta-build-tool-pack -D baseDir=. -D mbtVersion=$MBT_VERSION
            ls -la
            #artifactdeployer deploy --package-file ./cloud-mta-build-tool-pack --artifact-version $MBT_VERSION --repo-url http://nexusmil.wdf.sap.corp:8081/nexus/content/repositories/sap.milestones.manual-uploads.hosted --repo-user $MVN_REPO_USER --repo-passwd $MVN_REPO_PASSWD
  
workflows:
  version: 2
  build_integration:
    jobs:
      - build
  
  release:
    jobs:
      - release_new:
            filters:
              branches:
                only: develop
