# Golang CircleCI 2.0 configuration
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
  test:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: ~/workdir
    steps:
      - checkout
      - run: echo "INTEGRATION TEST !!!"
      
  deploy:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
     - run: echo "DEPLOY !!!"

workflows:
  version: 2
  
  on_pr_build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
              
  on_merge_build_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
              
  on_tag_build_test_deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
  #          tags:
  #            only: /.*/
            branches:
              only: /^v[0-9]+(\.[0-9])+(\.[0-9])/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `test`
 #           tags:
 #             only: /.*/
            branches:
              only: /^v[0-9]+(\.[0-9])+(\.[0-9])/
      - deploy:
          requires:
            - test
          filters:
#            tags:
#              only: /.*/
            branches:
              only: /^v[0-9]+(\.[0-9])+(\.[0-9])/
