# Golang CircleCI 2.0 configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
      
  release:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: bump new version
          command: |
            MBT_VERSION=$(cat ./VERSION)
            echo $MBT_VERSION
#      - run: 
#          name: release new version
#          command: curl -sL https://git.io/goreleaser | bash
#      - run: 
#          name: publish to npm
#          command: npm publish
  
workflows:
  version: 2
  build_integration:
    jobs:
      - build

  release_new:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v*/
