# Golang CircleCI 2.0 configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
      
  release_new:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: bump new version
          command: |        
            MBT_VERSION="0.0.0"
            echo 'export MBT_VERSION' >> $BASH_ENV
            command: echo New release ${MBT_VERSION}
      - run: 
          name: release new version
          command: echo New release ${MBT_VERSION}
      #- run: curl -sL https://git.io/goreleaser | bash
      #- run: npm publish .
      #- run: artifactdeployer pack --script-file ./configpack --package-file ./dist/cloud-mta-build-tool-pack -D baseDir=. -D mbtVersion=$MBT_VERSION
      #- run: artifactdeployer deploy --package-file ./dist/cloud-mta-build-tool-pack --artifact-version $MBT_VERSION --repo-url http://nexusmil.wdf.sap.corp:8081/nexus/content/repositories/sap.milestones.manual-uploads.hosted --repo-user $REPO_USER --repo-passwd $REPO_PASSWD
  
workflows:
  version: 2
  build_integration:
    jobs:
      - build
  
  release:
    jobs:
      - release_new:
            filters:
              branches:
                only: develop
