# Golang CircleCI 2.0 configuration
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    environment:
      - DEP_VERSION: 0.5.0
    working_directory: ~/workdir
    steps:
      - checkout
  test:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: ~/workdir
    steps:
      - checkout
      - run: echo "INTEGRATION TEST !!!"
      
  deploy:
    docker:
      - image: michdock/michdeploy:0.0.1
    working_directory: ~/workdir
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:7e:c8:28:cd:0b:94:b6:c8:f1:3f:71:40:a1:6e:fd"
      - checkout
      - run:
          name: remove dummy tag
          command: |
            git push https://github.com/michawai/aaa.git --delete dummy
      - run:
          name: bump version
          command: |
            CURR_MBT_VERSION=$(cat ./VERSION)
            echo "Current release: ${CURR_MBT_VERSION}"
            MBT_VERSION=$(echo $CURR_MBT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "New release: ${MBT_VERSION}"
            #Update new version in files
            sed  -i "s/${CURR_MBT_VERSION}/${MBT_VERSION}/" ./VERSION
            cat ./VERSION
            #Generate version file
            #go generate -run "go run ./internal/buildtools/embed.go -source=./configs/version.yaml -target=./internal/version/version_cfg.go -name=VersionConfig -package=version"
            #Add all updated files to commit
            git add .
            git config user.email "michawa@gmail.com"
            git config user.name "michawai"
            git commit -m "Bump version ${MBT_VERSION}"
            #Push commit directly to master
            git push https://github.com/michawai/aaa.git master
            #Tag
            git tag v${MBT_VERSION}
            git push https://github.com/michawai/aaa.git v${MBT_VERSION}
      - run:
          name: release new version
          command: |
            echo "run goreleaser"

workflows:
  version: 2
  
  on_pr_build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
              
  on_merge_build_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
              
  on_tag_build_test_deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /dummy/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /dummy/
            branches:
              ignore: /.*/

